app1/config/routes.rb
Rails.application.routes.draw do
  resources :huecos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app1/app/models/hueco.rb
class Hueco < ApplicationRecord
end

app1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app1/app/controllers/huecos_controller.rb
class HuecosController < ApplicationController
  before_action :set_hueco, only: [:show, :edit, :update, :destroy]

  # GET /huecos
  # GET /huecos.json
  def index
    @huecos = Hueco.all
  end

  # GET /huecos/1
  # GET /huecos/1.json
  def show
  end

  # GET /huecos/new
  def new
    @hueco = Hueco.new
  end

  # GET /huecos/1/edit
  def edit
  end

  # POST /huecos
  # POST /huecos.json
  def create
    @hueco = Hueco.new(hueco_params)

    respond_to do |format|
      if @hueco.save
        format.html { redirect_to @hueco, notice: 'Hueco was successfully created.' }
        format.json { render :show, status: :created, location: @hueco }
      else
        format.html { render :new }
        format.json { render json: @hueco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /huecos/1
  # PATCH/PUT /huecos/1.json
  def update
    respond_to do |format|
      if @hueco.update(hueco_params)
        format.html { redirect_to @hueco, notice: 'Hueco was successfully updated.' }
        format.json { render :show, status: :ok, location: @hueco }
      else
        format.html { render :edit }
        format.json { render json: @hueco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /huecos/1
  # DELETE /huecos/1.json
  def destroy
    @hueco.destroy
    respond_to do |format|
      format.html { redirect_to huecos_url, notice: 'Hueco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hueco
      @hueco = Hueco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hueco_params
      params.require(:hueco).permit(:localidad, :direccion, :tamanio, :ranking)
    end
end

app1/app/helpers/application_helper.rb
module ApplicationHelper
end

app1/app/helpers/huecos_helper.rb
module HuecosHelper
end

app1/app/views/huecos/_form.html.erb
<%= form_with(model: hueco, local: true) do |form| %>
  <% if hueco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hueco.errors.count, "error") %> prohibited this hueco from being saved:</h2>

      <ul>
      <% hueco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :localidad %>
    <%= form.text_field :localidad %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :tamanio %>
    <%= form.text_field :tamanio %>
  </div>

  <div class="field">
    <%= form.label :ranking %>
    <%= form.number_field :ranking %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app1/app/views/huecos/edit.html.erb
<h1>Editing Hueco</h1>

<%= render 'form', hueco: @hueco %>

<%= link_to 'Show', @hueco %> |
<%= link_to 'Back', huecos_path %>

app1/app/views/huecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Huecos</h1>

<table>
  <thead>
    <tr>
      <th>Localidad</th>
      <th>Direccion</th>
      <th>Tamanio</th>
      <th>Ranking</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @huecos.each do |hueco| %>
      <tr>
        <td><%= hueco.localidad %></td>
        <td><%= hueco.direccion %></td>
        <td><%= hueco.tamanio %></td>
        <td><%= hueco.ranking %></td>
        <td><%= link_to 'Show', hueco %></td>
        <td><%= link_to 'Edit', edit_hueco_path(hueco) %></td>
        <td><%= link_to 'Destroy', hueco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hueco', new_hueco_path %>

app1/app/views/huecos/new.html.erb
<h1>New Hueco</h1>

<%= render 'form', hueco: @hueco %>

<%= link_to 'Back', huecos_path %>

app1/app/views/huecos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Localidad:</strong>
  <%= @hueco.localidad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @hueco.direccion %>
</p>

<p>
  <strong>Tamanio:</strong>
  <%= @hueco.tamanio %>
</p>

<p>
  <strong>Ranking:</strong>
  <%= @hueco.ranking %>
</p>

<%= link_to 'Edit', edit_hueco_path(@hueco) %> |
<%= link_to 'Back', huecos_path %>

app1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>